#Requires -Version 5.1
<#
.SYNOPSIS
    CLAUDE.md/AGENTS.md three-level hierarchy test (Mission 173 step 5, Q17).

.DESCRIPTION
    Rerun with one command, from the repository root:

        powershell -NoProfile -ExecutionPolicy Bypass -File tests\test-claude-md-hierarchy.ps1

    Owner decision 2026-09-13 (Q17): CLAUDE.md and AGENTS.md carry the
    method by hierarchy at three levels -- workspace (<=10 lines, next to
    VAULT-ROOT.md, generated by tools/write-marker.sh), second-brain
    itself (existing file, <=200 lines, unchanged by this Mission since it
    already complies), and project (<=60 lines, generated by
    tools/project-bootstrap.sh, importing the method by @-reference rather
    than repeating it).

    Runs a real, full, silent install so the workspace-level files exist
    for real, then checks:
      1. line-count ceilings at all three levels;
      2. CLAUDE.md and AGENTS.md are byte-identical at the workspace and
         project levels (same content, both files -- the spec's own
         requirement);
      3. every @import line resolves to a real file on disk;
      4. HYPOTHESIS, not measured live: an actual Claude Code /memory (or
         Codex AGENTS.md) probe was not driven from this automated test --
         same fallback already applied by
         test-project-assistant-and-skills-links.ps1 for the same reason
         (Mesures prealables, regle 4).

    Exit code 0 means every assertion passed. Exit code 1 means at least one
    did not; details are printed to stdout as each check runs.
#>

[CmdletBinding()]
param([switch] $KeepTemp)

$ErrorActionPreference = 'Stop'
$RepoRoot = Split-Path $PSScriptRoot -Parent
$failures = New-Object System.Collections.Generic.List[string]

function Assert-True {
    param([bool] $Condition, [string] $Message)
    if ($Condition) { Write-Output "  PASS - $Message" }
    else { Write-Output "  FAIL - $Message"; $failures.Add($Message) | Out-Null }
}

function Get-LineCount {
    param([string] $Path)
    return @(Get-Content -Path $Path -Encoding UTF8).Count
}

function Assert-ImportsResolve {
    param([string] $FilePath, [string] $BaseDir)
    $lines = Get-Content -Path $FilePath -Encoding UTF8
    $importLines = @($lines | Where-Object { $_ -match '^@' })
    Assert-True ($importLines.Count -gt 0) "$FilePath has at least one @import"
    foreach ($importLine in $importLines) {
        $relativePath = $importLine.TrimStart('@')
        $resolved = Join-Path $BaseDir $relativePath
        Assert-True (Test-Path $resolved) "$FilePath's import '$importLine' resolves to a real file"
    }
}

$TestRoot = Join-Path $env:TEMP ("sb-claudemd-" + [Guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Force -Path $TestRoot | Out-Null
Write-Output ""
Write-Output "TestRoot: $TestRoot"

try {
    Write-Output ""
    Write-Output "=== Fresh install creates the workspace- and project-level files ==="
    $workspacePath = Join-Path $TestRoot 'workspace'
    $answersPath = Join-Path $TestRoot 'answers.json'
    $sampleAnswers = Get-Content -Raw -Path (Join-Path $PSScriptRoot 'fixtures\install-answers.sample.json') | ConvertFrom-Json
    $sampleAnswers.workspacePath = $workspacePath
    $sampleAnswers | ConvertTo-Json -Depth 10 | Set-Content -Path $answersPath -Encoding UTF8

    $installScript = Join-Path $RepoRoot 'install.ps1'
    $verdict = & $installScript -Source $RepoRoot -AnswersFile $answersPath -TestMode -TestRoot $TestRoot
    Assert-True ($LASTEXITCODE -eq 0) "install exits 0"
    Assert-True ($verdict -match 'Installation complete') "verdict reports success"

    $clonePath = Join-Path $workspacePath 'second-brain'
    $projectPath = Join-Path $workspacePath $sampleAnswers.firstProject.name

    Write-Output ""
    Write-Output "=== Level 1: workspace (next to VAULT-ROOT.md, <= 10 lines) ==="
    $wsClaudeMd = Join-Path $workspacePath 'CLAUDE.md'
    $wsAgentsMd = Join-Path $workspacePath 'AGENTS.md'
    Assert-True (Test-Path (Join-Path $workspacePath 'VAULT-ROOT.md')) "VAULT-ROOT.md exists (sanity: same level)"
    Assert-True (Test-Path $wsClaudeMd) "workspace CLAUDE.md exists"
    Assert-True (Test-Path $wsAgentsMd) "workspace AGENTS.md exists"
    $wsClaudeLines = Get-LineCount $wsClaudeMd
    Write-Output "  workspace CLAUDE.md: $wsClaudeLines lines"
    Assert-True ($wsClaudeLines -le 10) "workspace CLAUDE.md is 10 lines or fewer ($wsClaudeLines)"
    Assert-True ((Get-Content -Raw -Path $wsClaudeMd) -eq (Get-Content -Raw -Path $wsAgentsMd)) "workspace CLAUDE.md and AGENTS.md are byte-identical"
    $wsBody = Get-Content -Raw -Path $wsClaudeMd
    Assert-True ($wsBody -match [regex]::Escape('second-brain')) "workspace guide names the second-brain folder"
    Assert-True ($wsBody -match 'session-start') "workspace guide points at opening a session"
    Assert-True ($wsBody -match 'Demande') "workspace guide teaches the 'Demande a <nom>' formula"

    Write-Output ""
    Write-Output "=== Level 2: second-brain itself (existing file, <= 200 lines) ==="
    $sbClaudeMd = Join-Path $clonePath 'CLAUDE.md'
    $sbAgentsMd = Join-Path $clonePath 'AGENTS.md'
    $sbClaudeLines = Get-LineCount $sbClaudeMd
    $sbAgentsLines = Get-LineCount $sbAgentsMd
    Write-Output "  second-brain CLAUDE.md: $sbClaudeLines lines, AGENTS.md: $sbAgentsLines lines"
    Assert-True ($sbClaudeLines -le 200) "second-brain CLAUDE.md is 200 lines or fewer ($sbClaudeLines)"
    Assert-True ($sbAgentsLines -le 200) "second-brain AGENTS.md is 200 lines or fewer ($sbAgentsLines)"

    Write-Output ""
    Write-Output "=== Level 3: project (generated, <= 60 lines) ==="
    $projClaudeMd = Join-Path $projectPath 'CLAUDE.md'
    $projAgentsMd = Join-Path $projectPath 'AGENTS.md'
    Assert-True (Test-Path $projClaudeMd) "project CLAUDE.md exists"
    Assert-True (Test-Path $projAgentsMd) "project AGENTS.md exists"
    $projClaudeLines = Get-LineCount $projClaudeMd
    Write-Output "  project CLAUDE.md: $projClaudeLines lines"
    Assert-True ($projClaudeLines -le 60) "project CLAUDE.md is 60 lines or fewer ($projClaudeLines)"
    Assert-True ((Get-Content -Raw -Path $projClaudeMd) -eq (Get-Content -Raw -Path $projAgentsMd)) "project CLAUDE.md and AGENTS.md are byte-identical"

    Write-Output ""
    Write-Output "=== Every @import resolves to a real file ==="
    Assert-ImportsResolve -FilePath $projClaudeMd -BaseDir $projectPath
    Assert-ImportsResolve -FilePath $projAgentsMd -BaseDir $projectPath

    Write-Output ""
    Write-Output "=== Rerunning project-bootstrap.sh-driven creation is stable (no second project here, so re-verify write-marker.sh's own idempotency instead) ==="
    . (Join-Path $RepoRoot 'tools\resolve-bash-exe.ps1')
    $bashExe = Resolve-BashExe
    & $bashExe (Join-Path $clonePath 'tools\write-marker.sh') ($workspacePath -replace '\\', '/') $sampleAnswers.vaultName | Out-Null
    Assert-True ((Get-Content -Raw -Path $wsClaudeMd) -eq (Get-Content -Raw -Path $wsAgentsMd)) "workspace CLAUDE.md/AGENTS.md still identical after a rerun"
    Assert-True ((Get-LineCount $wsClaudeMd) -le 10) "workspace CLAUDE.md still <= 10 lines after a rerun"

    Write-Output ""
    Write-Output "=== HYPOTHESIS (not measured live in this environment) ==="
    Write-Output "  A running Claude Code session's own /memory (or Codex's own AGENTS.md"
    Write-Output "  hierarchy resolution) was not driven live from this automated test -- the"
    Write-Output "  file-level hierarchy and import resolution proven above is exactly what"
    Write-Output "  those mechanisms are documented to traverse (Mesures prealables, regle 4"
    Write-Output "  fallback: HYPOTHESE, poursuivre)."
}
finally {
    if (-not $KeepTemp) {
        Remove-Item -Recurse -Force -Path $TestRoot -ErrorAction SilentlyContinue
    }
    else {
        Write-Output ""
        Write-Output "Kept: $TestRoot"
    }
}

Write-Output ""
if ($failures.Count -gt 0) {
    Write-Output "=== FAILURES ($($failures.Count)) ==="
    $failures | ForEach-Object { Write-Output "  - $_" }
    exit 1
}
Write-Output "All assertions passed."
exit 0
