#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the wizard Skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_GITHUB_SECRET=() # GitHub Actions secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_github_secret NAME VALUE sets a GitHub Actions repo secret via gh.
# Use only when GitHub Actions is the configured CI provider. Falls back to a
# warning if gh is unavailable or unauthenticated.
set_github_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_GITHUB_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_github_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
# Use only when GitHub Actions is the configured CI provider.
set_github_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_GITHUB_SECRET[@]} )) && note "set ${#WRITTEN_GITHUB_SECRET[@]} GitHub secret(s): ${WRITTEN_GITHUB_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: authored for Mission 168, ticket 11 (Second Brain, guided
# acceptance list). Do not run this end to end from an agent session: it is
# built for the Owner, in person, after this Mission's local green (T14).
#
# Content source for every gesture / expected-observation pair below:
# acceptance scenarios defined during the build (workshop history, not
# distributed), read once while authoring this script, never at runtime.
# The three S7 test questions come from that same source. Order (S1..S10,
# S11 optional) follows it literally.
#
# This script never decides pass/fail: only the Owner, looking at their own
# screen, does. Every stage records "yes"/"no" plus an optional note; a "no"
# is written down and the wizard moves on to the next stage -- it never
# stops (ticket 11, criterion 2).
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=11

# --------------------------------------------------------------------------
# Additions to the library, authored by this ticket (still reusable,
# still testable in isolation -- see tests/test-acceptance-wizard-functions.sh).
# --------------------------------------------------------------------------

# Where this script lives, and the second-brain checkout it belongs to.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# SCENARIOS holds one "ID|verdict|note" entry per played scenario, verdict
# one of: yes, no, skipped. Pipe-delimited, so a note may never itself
# contain a literal "|" -- record_scenario sanitizes it before storing.
SCENARIOS=()

# _is_yes REPLY -- the reply parser: true (exit 0) for anything starting
# with y/Y, false otherwise (including an empty reply). Isolated on purpose
# so it can be unit-tested without a real prompt.
_is_yes() {
  [[ "$1" =~ ^[Yy] ]]
}

# _sanitize_note TEXT -- notes are stored pipe-delimited in SCENARIOS; a
# literal "|" typed by the Owner would corrupt the record, so it becomes "-".
_sanitize_note() {
  printf '%s' "${1//|/-}"
}

# record_scenario ID "Title" -- asks the one question every scenario ends
# on ("compliant?"), takes an optional free-text note either way, then
# appends "ID|yes|note" or "ID|no|note" to SCENARIOS. This is the point of
# the whole ticket: it never exits non-zero and never aborts the wizard --
# a "no" is data, not a failure (ticket 11, criterion 2).
record_scenario() {
  local id="$1" title="$2" reply="" note=""
  printf '  %s? %s -- compliant? [y/N]%s ' "$YELLOW" "$title" "$RESET"
  read -r reply || true
  printf '  %sOptional note (Enter to skip):%s ' "$DIM" "$RESET"
  read -r note || true
  note="$(_sanitize_note "$note")"
  if _is_yes "$reply"; then
    SCENARIOS+=("${id}|yes|${note}")
    printf '  %s✓ recorded%s %s: yes\n' "$GREEN" "$RESET" "$id"
  else
    SCENARIOS+=("${id}|no|${note}")
    printf '  %s✗ recorded%s %s: no (continuing)\n' "$RED" "$RESET" "$id"
  fi
}

# record_skipped ID "note" -- for the optional S11 when the Owner declines it.
record_skipped() {
  SCENARIOS+=("$1|skipped|$2")
}

# resolve_report_path [OUT] -- default: a sibling file next to this
# checkout, timestamped (never inside it: ticket 11's own requirement --
# the finished report must never enter a repository a later Owner push
# makes public). A custom OUT is honoured, but still refused if it resolves
# inside REPO_ROOT: caught here, not discovered after a push.
resolve_report_path() {
  local out="${1:-}"
  local path
  if [[ -n "$out" ]]; then
    path="$out"
  else
    local workspace_root
    workspace_root="$(cd "$REPO_ROOT/.." && pwd)"
    path="$workspace_root/second-brain-acceptance-$(date +%Y%m%d-%H%M%S).md"
  fi
  case "$path" in
    /*) : ;;
    *) path="$(pwd)/$path" ;;
  esac
  case "$path" in
    "$REPO_ROOT"/*|"$REPO_ROOT")
      printf 'Error: report path %s is inside %s -- pick a path outside second-brain.\n' "$path" "$REPO_ROOT" >&2
      return 1
      ;;
  esac
  printf '%s' "$path"
}

# write_report PATH -- renders SCENARIOS to a Markdown file at PATH: a
# title, a timestamp, the local repo's HEAD (proof this ran against the
# unpushed local source, T23), the assistant name used at S7, then one
# table row per scenario.
write_report() {
  local path="$1" sha
  sha="$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")"
  {
    printf '# Second Brain -- guided acceptance report\n\n'
    # `--` ends option parsing: without it, bash's printf builtin mistakes a
    # format string starting with "- " for an (invalid) option flag. Found
    # by tests/test-acceptance-wizard-functions.sh (case 10), which is
    # exactly why these lines get their own isolated test instead of only
    # being read by eye.
    printf -- '- Date: %s\n' "$(date '+%Y-%m-%d %H:%M:%S %z')"
    printf -- '- Local source: %s\n' "$REPO_ROOT"
    printf -- '- HEAD: %s\n' "$sha"
    printf -- '- Assistant name used for S7: %s\n\n' "${ASSISTANT_NAME:-N/A}"
    printf '| Scenario | Compliant | Note |\n'
    printf '|---|---|---|\n'
    local entry id verdict note
    for entry in "${SCENARIOS[@]}"; do
      IFS='|' read -r id verdict note <<<"$entry"
      printf '| %s | %s | %s |\n' "$id" "$verdict" "$note"
    done
  } > "$path"
  printf '  %s✓ wrote%s acceptance report -> %s\n' "$GREEN" "$RESET" "$path"
}

# usage_and_exit -- prints usage then exits 1 (bad arguments only).
usage_and_exit() {
  cat >&2 <<'EOF'
Usage: acceptance-wizard.sh [--out PATH]

  --out PATH   Where to write the final report (default: a sibling file
               next to this second-brain checkout, timestamped). PATH must
               resolve outside this repository.
EOF
  exit 1
}

main() {
  local out_path=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --out) out_path="${2:-}"; shift 2 ;;
      --out=*) out_path="${1#*=}"; shift ;;
      -h|--help) usage_and_exit ;;
      *) printf 'Unknown argument: %s\n' "$1" >&2; usage_and_exit ;;
    esac
  done

  local report_path
  report_path="$(resolve_report_path "$out_path")" || exit 1

  banner "Second Brain -- guided acceptance (S1-S10, optional S11)"
  say "Source: $REPO_ROOT"
  say "HEAD:   $(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown) (local, unpushed clone -- T23)"
  say "Report will be written to: $report_path"

  stage "S1 -- Fresh install, Windows"
  step "From a brand-new, empty workspace folder, in PowerShell, run the"
  step "installer against THIS local checkout:"
  step "  $REPO_ROOT\\install.ps1 -Source \"$REPO_ROOT\""
  step "Answer the questionnaire as it appears."
  note "Expected: no Windows prompt of any kind; the run ends on a one-line"
  note "success verdict (catalog key verdict.success, e.g. EN \"Installation"
  note "complete: everything is in place.\"); every check in playbook §4"
  note "holds (workspace marker, USER.md filled in with no template field"
  note "left, guardians installed, a skill folder per deployed skill, the"
  note "assistant sub-agent listed, first project registered)."
  record_scenario "S1" "Fresh install, Windows"

  stage "S2 -- Re-run without changes"
  step "Re-run the exact same installer command a second time, unchanged."
  note "Expected: no file modified (porcelain empty in the clone -- there is"
  note "no project yet, S4 creates the first one), the same one-line verdict"
  note "as S1."
  record_scenario "S2" "Re-run without changes"

  stage "S3 -- Resume after a forced stop"
  step "Start the installer, then close the terminal partway through, before"
  step "it finishes."
  step "Re-run the exact same installer command."
  note "Expected: it resumes where it left off (no question or step already"
  note "answered is replayed), nothing already written is overwritten, and"
  note "it ends on the same success verdict as S1."
  record_scenario "S3" "Resume after a forced stop"

  stage "S4 -- First project"
  step "Create a project named \"atelier-test\" (the installer's own"
  step "first-project step, or a re-run in update mode)."
  note "Expected: a line in projects/PROJECT-REGISTRY.md, a project sheet,"
  note "an AGENTS.md/CLAUDE.md pointer inside the new project, guardians"
  note "pinned (repo: local), and a trial commit inside that project"
  note "accepted by its guardians."
  record_scenario "S4" "First project"

  stage "S5 -- A guardian refuses"
  step "Inside the new project, add a file containing a fake secret (a line"
  step "matching one of the patterns in rules/patterns/secret-patterns.txt,"
  step "e.g. ghp_ followed by 20+ letters/digits), then commit."
  note "Expected: a readable refusal (check-secrets.sh: \"REFUS : motif de"
  note "secret detecte.\")."
  step "Remove the secret, commit again."
  note "Expected: this second commit is accepted."
  record_scenario "S5" "A guardian refuses, then accepts"

  stage "S6 -- Cold session"
  step "Open Claude Code in second-brain (this checkout) and run the"
  step "session-start skill."
  note "Expected: READY is the very first line of its output (Mission 156's"
  note "own criterion)."
  record_scenario "S6" "Cold session (session-start)"

  stage "S7 -- The assistant"
  ask ASSISTANT_NAME "What name did you give your assistant? [Enter = Brian]"
  ASSISTANT_NAME="${ASSISTANT_NAME:-Brian}"
  step "Ask $ASSISTANT_NAME (Claude Code sub-agent, claude.ai Project, or"
  step "custom GPT -- whichever you set up) these three questions, one at a"
  step "time (T07):"
  step "  1. \"How do I open a session?\""
  note "     Expected: cites the session-start skill and its reading list."
  step "  2. \"What is a Mission, and where do I write one?\""
  note "     Expected: cites the Mission template and the project operating"
  note "     model brief V2 -- in the project, not in second-brain itself."
  step "  3. \"Create me a test file.\""
  note "     Expected: refuses, explains it is read-only, points to doing"
  note "     it yourself or with your main agent instead."
  record_scenario "S7" "$ASSISTANT_NAME answers correctly, cites sources, refuses to write"

  stage "S8 -- Web skills"
  step "Open the web skills package folder (produced by the installer) and"
  step "upload two of its zip files into a claude.ai Project, one at a time."
  note "Expected: both skills appear in the Project and trigger when used."
  record_scenario "S8" "Web skills upload and trigger"

  stage "S9 -- No Git, no admin rights"
  step "On a standard (non-administrator) Windows profile with no Git on"
  step "PATH, paste the install line (or run"
  step "install.ps1 -Source \"$REPO_ROOT\" the same way)."
  note "Expected: Git, Python and pre-commit all get installed inside the"
  note "user profile, no elevation prompt of any kind, and the run still"
  note "ends on the success verdict."
  record_scenario "S9" "No Git, no admin rights"

  stage "S10 -- Offline"
  step "Disconnect the network, then make a commit inside the project."
  note "Expected: the guardians still run and still decide (accept or"
  note "refuse) with no network call."
  record_scenario "S10" "Offline commit"

  stage "S11 (optional) -- macOS or Linux"
  if confirm "Run the optional S11 now (macOS or Linux available)?"; then
    step "Using install.sh instead of install.ps1, replay S1, S2 and S4:"
    step "  $REPO_ROOT/install.sh --source \"$REPO_ROOT\""
    note "Expected: same outcomes as S1, S2 and S4 above, on this platform."
    record_scenario "S11" "macOS/Linux replay of S1, S2, S4"
  else
    say "Skipped (optional)."
    record_skipped "S11" "optional stage, not run"
  fi

  write_report "$report_path"
  finish
}

# Sourcing this file (tests/test-acceptance-wizard-functions.sh does exactly
# that) must define the functions above without running the interactive
# wizard: only run main when this file is the one actually executed.
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  main "$@"
fi
