#!/usr/bin/env bash
# Updates an INSTALLED Second Brain to a published version (Decision 152251
# B3, Mission 191-C01): `second-brain update <version>`.
#
# An installed Vault is a clone of the published repository with the
# participant's own commits on top (USER.md, VAULT-IDENTITY.md, project
# sheets and registry, indexes). Receiving a version is a merge, never a copy
# and never a reinstallation:
#   1. refusals before anything is touched: the Vault has uncommitted
#      changes; it has no generated identity; its `origin` is the
#      bootstrap's temporary clone (installation older than v0.1.4, Mission
#      185) -- the refusal explains that such an installation is reinstalled;
#   2. `git fetch --tags origin`; the version must be a tag there;
#   3. the version already in HEAD's history: "already up to date", exit 0 --
#      unless the assistant's forms are stale (the version was merged by a
#      tool older than Mission 223): they are then regenerated as in 5b, in
#      one guarded commit of their own, and the verdict is UPDATED;
#  3b. handover (Mission 231, D3 of Mission 230): when the version's own
#      tools/second-brain-update.sh differs from this one, it is run instead
#      (extracted from the tag, --vault), once, and its code is returned; a
#      version without that tool is refused;
#   4. `git merge --no-ff --no-commit <version>`: the participant's commits are
#      kept. Two conflicts are expected and resolved, each in its own way:
#      generated indexes (`index.md`, rebuilt locally by
#      tools/build-indexes.sh) take the version's side and are regenerated
#      after the merge rather than resolved by hand; `USER.md`, the profile the
#      installer writes whole from the participant's answers, keeps the
#      participant's side byte for byte and gains only what the new skeleton
#      adds and they do not have -- a front-matter key, a section heading
#      (Mission 230, P1 of report 227; see resolve_user_profile below). Any
#      other conflict, including any other file of the participant: `git merge
#      --abort`, refusal naming the files, HEAD unchanged;
#   5. identity checked: `vault_id` after the merge = `vault_id` before, or
#      abort and refusal;
#  5b. the assistant's three forms (.claude/agents/<slug>.md,
#      .agents/skills/<slug>/, web-package/<slug>/) regenerated by the
#      version's own generator (sb_installer_helper.py render-assistant,
#      Mission 223), with the name the installer recorded in its carnet
#      (.install/state.json: assistant.name, else answers.vaultName) and the
#      language recorded there -- never the default name. No recorded name:
#      nothing is generated and the message says so. A generator failure:
#      abort and refusal;
#   6. indexes regenerated by the version's own tools/build-indexes.sh, the
#      session preflight stamped, then ONE merge commit through the Vault's
#      guardians (never bypassed). Refused by a guardian: abort, HEAD
#      unchanged, the guardian's output shown.
# Touches only this Vault -- never the profile, never a tool configuration --
# with one exception (Mission 237): in each project of the registry, a link to
# a skill renamed by the version (tools/skill-renames.tsv), now pointing
# nowhere, is replaced by the link under the new name, and the project's
# journal gets one line; any other dead link is named, never touched. Birth certificates keep their `vault_ref` (it records the
# birth, not the current version). If the MCP server changed, the message
# says to run tools/install-vault-mcp.sh again.
#
# Closed verdict on the last line: UPDATED, UP-TO-DATE or REFUSED.
# Messages through the i18n/ catalogues (FR, EN, ES).
#
# usage: second-brain-update.sh <version> [--vault <root>] [--lang FR|EN|ES]

set -u

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "$SCRIPT_DIR/lib/tmp.sh"  # declared temporary folder (Mission 234)
VAULT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
VERSION=""
LANGUAGE=""

usage() {
  echo "usage: second-brain-update.sh <version> [--vault <racine>] [--lang FR|EN|ES]" >&2
}

while [ $# -gt 0 ]; do
  case "$1" in
    --vault)
      [ $# -ge 2 ] || { usage; exit 1; }
      VAULT_ROOT="$(cd "$2" 2>/dev/null && pwd)" || { usage; exit 1; }
      shift 2 ;;
    --lang)
      [ $# -ge 2 ] || { usage; exit 1; }
      LANGUAGE="$2"; shift 2 ;;
    -*) usage; exit 1 ;;
    *)
      [ -z "$VERSION" ] || { usage; exit 1; }
      VERSION="$1"; shift ;;
  esac
done
[ -n "$VERSION" ] || { usage; exit 1; }

# Run from inside the Vault it updates, this very file would be rewritten by
# the merge while bash is still reading it: it first copies its tools and
# catalogues to a temporary folder and runs from there (removed at the end).
case "$SCRIPT_DIR/" in
  "$VAULT_ROOT"/*)
    if [ -z "${SB_UPDATE_TMP:-}" ]; then
      SB_UPDATE_TMP="$(mktemp -d "$(sb_tmp_dir tools)/sb-update-XXXXXX")" || exit 1
      cp -R "$VAULT_ROOT/tools" "$VAULT_ROOT/i18n" "$SB_UPDATE_TMP/" || exit 1
      export SB_UPDATE_TMP
      exec bash "$SB_UPDATE_TMP/tools/second-brain-update.sh" "$VERSION" --vault "$VAULT_ROOT" ${LANGUAGE:+--lang "$LANGUAGE"}
    fi
    ;;
esac
if [ -n "${SB_UPDATE_TMP:-}" ] && [ "$SCRIPT_DIR" = "$SB_UPDATE_TMP/tools" ]; then
  trap 'rm -rf "$SB_UPDATE_TMP"' EXIT
fi

# Messages: this script's own catalogues (a v0.1.7 installation, updated by
# the script of the version it receives, has no update keys yet). Language:
# the one the installer recorded (.install/state.json), else English.
if [ -z "$LANGUAGE" ]; then
  LANGUAGE="$(tr -d '\r' < "$VAULT_ROOT/.install/state.json" 2>/dev/null | sed -n 's/.*"language"[[:space:]]*:[[:space:]]*"\([A-Za-z]*\)".*/\1/p' | head -n 1)"
fi
[ -n "$LANGUAGE" ] || LANGUAGE="EN"
OWN_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CATALOG_FILE="$OWN_ROOT/i18n/catalog.$(printf '%s' "$LANGUAGE" | tr '[:upper:]' '[:lower:]').json"
[ -f "$CATALOG_FILE" ] || CATALOG_FILE="$OWN_ROOT/i18n/catalog.en.json"
HELPER="$SCRIPT_DIR/sb_installer_helper.py"

CATALOG() {
  uv run --no-project "$HELPER" format-catalog "$CATALOG_FILE" "$@"
}

native() {
  if command -v cygpath >/dev/null 2>&1; then
    cygpath -w "$1"
  else
    printf '%s\n' "$1"
  fi
}

refuse() {
  CATALOG "$@"
  echo "VERDICT: REFUSED"
  exit 1
}

. "$SCRIPT_DIR/vault-identity.sh"

G() { git -C "$VAULT_ROOT" "$@"; }

# --- 1. Refusals before anything is touched ---------------------------------
G rev-parse --git-dir >/dev/null 2>&1 || refuse "sbUpdate.notAClone" "$(native "$VAULT_ROOT")"
DIRTY="$(G status --porcelain)"
if [ -n "$DIRTY" ]; then
  refuse "sbUpdate.dirty" "$(printf '%s\n' "$DIRTY" | cut -c4- | head -n 5 | tr '\n' ' ')"
fi
ID_BEFORE="$(vid_get "$VAULT_ROOT" vault_id)"
[ "$(vid_get "$VAULT_ROOT" status)" = "generated" ] && [ -n "$ID_BEFORE" ] \
  || refuse "sbUpdate.noIdentity" "$(native "$VAULT_ROOT/VAULT-IDENTITY.md")"
ORIGIN="$(G config --get remote.origin.url 2>/dev/null | head -n 1)"
[ -n "$ORIGIN" ] || refuse "sbUpdate.noOrigin"
# Before Mission 185 the installed clone kept the bootstrap's temporary
# clone as its origin (%TEMP%\second-brain-install): nothing to fetch from.
case "$(printf '%s' "$ORIGIN" | tr '\\' '/' | sed 's#/*$##')" in
  */second-brain-install) refuse "sbUpdate.temporaryOrigin" "$ORIGIN" ;;
esac
SERVER_BEFORE="$(vid_server_name "$VAULT_ROOT" 2>/dev/null || true)"
HEAD_BEFORE="$(G rev-parse HEAD)"

# --- 2. Fetch; the version must be a published tag --------------------------
G fetch --quiet --tags origin 2>/dev/null || refuse "sbUpdate.fetchFailed" "$ORIGIN"
TARGET="$(G rev-parse --verify --quiet "refs/tags/$VERSION^{commit}")"
[ -n "$TARGET" ] || refuse "sbUpdate.noSuchVersion" "$VERSION" "$ORIGIN"

# relink_projects (Mission 237): the projects of the registry get the links of
# the skills the version renamed, through the version's own helper; one journal
# line per project that changed. Never fails the update: a problem is named.
relink_projects() {
  local out line project sub old new base
  out="$(uv run --no-project "$VAULT_ROOT/tools/sb_installer_helper.py" relink-renamed "$VAULT_ROOT" --registry 2>/dev/null | tr -d '\r')" || return 0
  while IFS= read -r line; do
    case "$line" in
      "RELINKED "*)
        IFS="$(printf '\t')" read -r project sub old new <<EOF
${line#RELINKED }
EOF
        CATALOG "sbUpdate.relinked" "$(native "$project")" "$old" "$new" ;;
      "DEAD "*) CATALOG "sbUpdate.deadLink" "$(native "${line#DEAD }")" ;;
      "JOURNAL "*)
        base="${line#JOURNAL *	}"
        bash "$VAULT_ROOT/tools/append-journal.sh" "$base" "APPLY:update -- $VERSION : liens des skills renommees refaits par second-brain-update (tools/skill-renames.tsv)" >/dev/null 2>&1 || true ;;
    esac
  done <<EOF
$out
EOF
}

# Step 5b, also played by step 3. Reads the name from the carnet, runs the
# generator of the tree now checked out (the version's), stages the three
# forms. Returns 1 if the generator fails; no recorded name is not a failure.
ASSISTANT_NAME=""
regenerate_assistant() {
  local carnet="$VAULT_ROOT/.install/state.json" language slug
  ASSISTANT_NAME=""
  if [ -f "$carnet" ]; then
    ASSISTANT_NAME="$(uv run --no-project "$HELPER" field "$carnet" assistant.name 2>/dev/null | tr -d '\r')"
    [ -n "$ASSISTANT_NAME" ] \
      || ASSISTANT_NAME="$(uv run --no-project "$HELPER" field "$carnet" answers.vaultName 2>/dev/null | tr -d '\r')"
  fi
  if [ -z "$ASSISTANT_NAME" ]; then
    CATALOG "sbUpdate.assistantNoName" "$(native "$carnet")"
    return 0
  fi
  language="$(uv run --no-project "$HELPER" field "$carnet" answers.language 2>/dev/null | tr -d '\r' | tr '[:lower:]' '[:upper:]')"
  case "$language" in FR|EN|ES) ;; *) language="EN" ;; esac
  slug="$(uv run --no-project "$VAULT_ROOT/tools/sb_installer_helper.py" render-assistant "$VAULT_ROOT" "$ASSISTANT_NAME" --language "$language" 2>/dev/null | tr -d '\r' | tail -n 1)"
  [ -n "$slug" ] || return 1
  G add -A -- ".claude/agents/$slug.md" ".agents/skills/$slug" "web-package/$slug" >/dev/null 2>&1 || return 1
  return 0
}

# --- 3. Already there --------------------------------------------------------
if G merge-base --is-ancestor "$TARGET" HEAD; then
  if ! regenerate_assistant; then
    # The tree was clean at step 1: everything changed here is the generator's.
    G reset --quiet --hard HEAD >/dev/null 2>&1
    refuse "sbUpdate.assistantFailed" "$VERSION"
  fi
  if [ -n "$(G status --porcelain)" ]; then
    bash "$VAULT_ROOT/tools/session-preflight.sh" >/dev/null 2>&1 || true
    COMMIT_OUT="$(G commit --quiet --no-edit -m "Regenerate assistant forms for second-brain $VERSION" 2>&1)"
    if [ $? -ne 0 ]; then
      G reset --quiet --hard HEAD >/dev/null 2>&1
      printf '%s\n' "$COMMIT_OUT" | tail -n 20
      refuse "sbUpdate.guardiansRefused" "$VERSION"
    fi
    CATALOG "sbUpdate.assistantRegenerated" "$VERSION" "$ASSISTANT_NAME" "$(G rev-parse --short HEAD)"
    relink_projects
    echo "VERDICT: UPDATED"
    exit 0
  fi
  relink_projects
  CATALOG "sbUpdate.upToDate" "$VERSION"
  echo "VERDICT: UP-TO-DATE"
  exit 0
fi

# --- 3b. Hand over to the version's own tool (Mission 231) --------------------
# The tool that merges a version is that version's, not this one: when a
# version changes how an update is done (Mission 230: the USER.md resolution
# lived in the new tool only), the installed tool would merge by the old rules
# and refuse. Once the version is fetched and before anything is merged, this
# tool compares its own text with the version's tools/second-brain-update.sh
# (line endings ignored). When they differ it extracts the version's tools/
# and i18n/ into a temporary folder, runs that tool with --vault, and exits
# with its code; the version's verdict is the last line. SB_UPDATE_DELEGATED
# marks the tool run this way: it never hands over again, so there is no loop.
# A version without an update tool is refused: nothing would merge it.
# This cannot repair an installation whose tool predates this section
# (v0.1.14 and earlier): that tool never gets here. For those, the version's
# tool is run with --vault, as the update skill says; only the updates after
# that one hand over by themselves.
if [ -z "${SB_UPDATE_DELEGATED:-}" ]; then
  G cat-file -e "$TARGET:tools/second-brain-update.sh" 2>/dev/null \
    || refuse "sbUpdate.receivedToolMissing" "$VERSION" "tools/second-brain-update.sh"
  OWN_SUM="$(tr -d '\r' < "$SCRIPT_DIR/second-brain-update.sh" | git hash-object --stdin)"
  RECEIVED_SUM="$(G show "$TARGET:tools/second-brain-update.sh" | tr -d '\r' | git hash-object --stdin)"
  if [ "$RECEIVED_SUM" != "$OWN_SUM" ]; then
    HANDOVER_DIR="$(mktemp -d "$(sb_tmp_dir tools)/sb-update-received-XXXXXX")" \
      || refuse "sbUpdate.handoverFailed" "$VERSION"
    HANDOVER_PATHS="tools"
    G cat-file -e "$TARGET:i18n" 2>/dev/null && HANDOVER_PATHS="tools i18n"
    # shellcheck disable=SC2086 -- two plain folder names
    if ! G archive --format=tar "$TARGET" $HANDOVER_PATHS | tar -xf - -C "$HANDOVER_DIR" \
      || [ ! -f "$HANDOVER_DIR/tools/second-brain-update.sh" ]; then
      rm -rf "$HANDOVER_DIR"
      refuse "sbUpdate.handoverFailed" "$VERSION"
    fi
    CATALOG "sbUpdate.handover" "$VERSION"
    echo "SB-UPDATE-HANDOVER: $VERSION"
    SB_UPDATE_DELEGATED=1 SB_UPDATE_TMP="$HANDOVER_DIR" \
      bash "$HANDOVER_DIR/tools/second-brain-update.sh" "$VERSION" --vault "$VAULT_ROOT" --lang "$LANGUAGE"
    HANDOVER_RC=$?
    rm -rf "$HANDOVER_DIR"
    exit "$HANDOVER_RC"
  fi
fi

abort_merge() {
  G merge --abort >/dev/null 2>&1 || true
  if [ "$(G rev-parse HEAD)" != "$HEAD_BEFORE" ]; then
    CATALOG "sbUpdate.headMoved" "$HEAD_BEFORE"
  fi
}

# Step 4, for USER.md only (Mission 230, P1 of report 227). The participant's
# profile is written whole by the installer from their answers; the version
# distributes the empty skeleton. Every change of that skeleton -- the
# `language:` line of v0.1.15 among them -- therefore conflicts with every
# installation, and the update ended REFUSED for all of them.
# The resolution keeps the participant's side byte for byte and appends only
# what the new skeleton adds and they do not have (a front-matter key, a
# section heading): tools/sb_installer_helper.py merge-user-profile, the
# generator's own counterpart, taken from the tree the merge has just checked
# out -- the version's, as step 5b and step 6 already do. Returns 1 when it
# cannot be done, and the file then goes back to the named conflicts: a
# refusal, never a silent resolution. No other file of the participant is
# resolved here.
resolve_user_profile() {
  local work ours theirs lang rc
  work="$(mktemp -d "$(sb_tmp_dir tools)/sb-profile-XXXXXX")" || return 1
  ours="$work/ours.md"
  theirs="$work/theirs.md"
  rc=1
  if G show :2:USER.md > "$ours" 2>/dev/null && G show :3:USER.md > "$theirs" 2>/dev/null; then
    lang="$(uv run --no-project "$HELPER" field "$VAULT_ROOT/.install/state.json" answers.language 2>/dev/null \
      | tr -d '\r' | tr '[:upper:]' '[:lower:]')"
    case "$lang" in fr|en|es) ;; *) lang="" ;; esac
    if uv run --no-project "$VAULT_ROOT/tools/sb_installer_helper.py" merge-user-profile \
      "$ours" "$theirs" "$work/merged.md" ${lang:+--language "$lang"} >/dev/null 2>&1; then
      cp "$work/merged.md" "$VAULT_ROOT/USER.md" && rc=0
    fi
  fi
  rm -rf "$work"
  return $rc
}

# --- 4. Merge, without committing yet ----------------------------------------
G -c merge.renames=true merge --no-ff --no-commit --quiet "refs/tags/$VERSION" >/dev/null 2>&1
CONFLICTS="$(G diff --name-only --diff-filter=U)"
if [ -n "$CONFLICTS" ]; then
  OTHERS=""
  while IFS= read -r f; do
    [ -z "$f" ] && continue
    if [ "$f" = "USER.md" ]; then
      if resolve_user_profile; then G add -- USER.md; else OTHERS="${OTHERS}${OTHERS:+ }$f"; fi
      continue
    fi
    case "$(basename "$f")" in
      index.md) G checkout --theirs -- "$f" >/dev/null 2>&1 && G add -- "$f" ;;
      *) OTHERS="${OTHERS}${OTHERS:+ }$f" ;;
    esac
  done <<EOF
$CONFLICTS
EOF
  if [ -n "$OTHERS" ]; then
    abort_merge
    refuse "sbUpdate.conflict" "$VERSION" "$OTHERS"
  fi
fi

# --- 5. Identity unchanged ---------------------------------------------------
ID_AFTER="$(vid_get "$VAULT_ROOT" vault_id)"
if [ "$ID_AFTER" != "$ID_BEFORE" ] || [ "$(vid_get "$VAULT_ROOT" status)" != "generated" ]; then
  abort_merge
  refuse "sbUpdate.identityChanged" "$ID_BEFORE" "${ID_AFTER:-(none)}"
fi

# --- 5b. The assistant's forms, from the version's generator ------------------
if ! regenerate_assistant; then
  abort_merge
  refuse "sbUpdate.assistantFailed" "$VERSION"
fi

# --- 6. Indexes regenerated, preflight, one guarded merge commit -------------
if [ -f "$VAULT_ROOT/tools/build-indexes.sh" ]; then
  bash "$VAULT_ROOT/tools/build-indexes.sh" "$VAULT_ROOT" >/dev/null 2>&1 || {
    abort_merge
    refuse "sbUpdate.indexesFailed" "$VERSION"
  }
  G add -A -- ':(glob)**/index.md' >/dev/null 2>&1 || true
fi
bash "$VAULT_ROOT/tools/session-preflight.sh" >/dev/null 2>&1 || true
COMMIT_OUT="$(G commit --quiet --no-edit -m "Update to second-brain $VERSION" 2>&1)"
if [ $? -ne 0 ]; then
  abort_merge
  printf '%s\n' "$COMMIT_OUT" | tail -n 20
  refuse "sbUpdate.guardiansRefused" "$VERSION"
fi

PORCELAIN="$(G status --porcelain)"
CATALOG "sbUpdate.done" "$VERSION" "$(G rev-parse --short HEAD)"
[ -z "$PORCELAIN" ] || CATALOG "sbUpdate.leftovers" "$(printf '%s\n' "$PORCELAIN" | cut -c4- | head -n 5 | tr '\n' ' ')"
SERVER_AFTER="$(vid_server_name "$VAULT_ROOT" 2>/dev/null || true)"
if [ "$SERVER_AFTER" != "$SERVER_BEFORE" ] || ! grep -q 'vid_server_name' "$VAULT_ROOT/tools/install-vault-mcp.sh" 2>/dev/null \
  || [ "$(G diff --name-only "$HEAD_BEFORE" HEAD -- tools/install-vault-mcp.sh tools/vault-mcp.py | head -n 1)" != "" ]; then
  CATALOG "sbUpdate.rerunMcp" "$(native "$VAULT_ROOT/tools/install-vault-mcp.sh")"
fi
relink_projects
echo "VERDICT: UPDATED"
exit 0
