#!/usr/bin/env bash
# Updates an INSTALLED Second Brain to a published version (Decision 152251
# B3, Mission 191-C01): `second-brain update <version>`.
#
# An installed Vault is a clone of the published repository with the
# participant's own commits on top (USER.md, VAULT-IDENTITY.md, project
# sheets and registry, indexes). Receiving a version is a merge, never a copy
# and never a reinstallation:
#   1. refusals before anything is touched: the Vault has uncommitted
#      changes; it has no generated identity; its `origin` is the
#      bootstrap's temporary clone (installation older than v0.1.4, Mission
#      185) -- the refusal explains that such an installation is reinstalled;
#   2. `git fetch --tags origin`; the version must be a tag there;
#   3. the version already in HEAD's history: "already up to date", exit 0;
#   4. `git merge --no-ff --no-commit <version>`: the participant's commits are
#      kept. Conflicts on generated indexes (`index.md`, rebuilt locally by
#      tools/build-indexes.sh) are expected: they take the version's side and
#      are regenerated after the merge rather than resolved by hand. Any
#      other conflict: `git merge --abort`, refusal naming the files, HEAD
#      unchanged;
#   5. identity checked: `vault_id` after the merge = `vault_id` before, or
#      abort and refusal;
#   6. indexes regenerated by the version's own tools/build-indexes.sh, the
#      session preflight stamped, then ONE merge commit through the Vault's
#      guardians (never bypassed). Refused by a guardian: abort, HEAD
#      unchanged, the guardian's output shown.
# Touches only this Vault: never a project, never the profile, never a tool
# configuration. Birth certificates keep their `vault_ref` (it records the
# birth, not the current version). If the MCP server changed, the message
# says to run tools/install-vault-mcp.sh again.
#
# Closed verdict on the last line: UPDATED, UP-TO-DATE or REFUSED.
# Messages through the i18n/ catalogues (FR, EN, ES).
#
# usage: second-brain-update.sh <version> [--vault <root>] [--lang FR|EN|ES]

set -u

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
VAULT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
VERSION=""
LANGUAGE=""

usage() {
  echo "usage: second-brain-update.sh <version> [--vault <racine>] [--lang FR|EN|ES]" >&2
}

while [ $# -gt 0 ]; do
  case "$1" in
    --vault)
      [ $# -ge 2 ] || { usage; exit 1; }
      VAULT_ROOT="$(cd "$2" 2>/dev/null && pwd)" || { usage; exit 1; }
      shift 2 ;;
    --lang)
      [ $# -ge 2 ] || { usage; exit 1; }
      LANGUAGE="$2"; shift 2 ;;
    -*) usage; exit 1 ;;
    *)
      [ -z "$VERSION" ] || { usage; exit 1; }
      VERSION="$1"; shift ;;
  esac
done
[ -n "$VERSION" ] || { usage; exit 1; }

# Run from inside the Vault it updates, this very file would be rewritten by
# the merge while bash is still reading it: it first copies its tools and
# catalogues to a temporary folder and runs from there (removed at the end).
case "$SCRIPT_DIR/" in
  "$VAULT_ROOT"/*)
    if [ -z "${SB_UPDATE_TMP:-}" ]; then
      SB_UPDATE_TMP="$(mktemp -d "${TMPDIR:-/tmp}/sb-update-XXXXXX")" || exit 1
      cp -R "$VAULT_ROOT/tools" "$VAULT_ROOT/i18n" "$SB_UPDATE_TMP/" || exit 1
      export SB_UPDATE_TMP
      exec bash "$SB_UPDATE_TMP/tools/second-brain-update.sh" "$VERSION" --vault "$VAULT_ROOT" ${LANGUAGE:+--lang "$LANGUAGE"}
    fi
    ;;
esac
if [ -n "${SB_UPDATE_TMP:-}" ] && [ "$SCRIPT_DIR" = "$SB_UPDATE_TMP/tools" ]; then
  trap 'rm -rf "$SB_UPDATE_TMP"' EXIT
fi

# Messages: this script's own catalogues (a v0.1.7 installation, updated by
# the script of the version it receives, has no update keys yet). Language:
# the one the installer recorded (.install/state.json), else English.
if [ -z "$LANGUAGE" ]; then
  LANGUAGE="$(tr -d '\r' < "$VAULT_ROOT/.install/state.json" 2>/dev/null | sed -n 's/.*"language"[[:space:]]*:[[:space:]]*"\([A-Za-z]*\)".*/\1/p' | head -n 1)"
fi
[ -n "$LANGUAGE" ] || LANGUAGE="EN"
OWN_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CATALOG_FILE="$OWN_ROOT/i18n/catalog.$(printf '%s' "$LANGUAGE" | tr '[:upper:]' '[:lower:]').json"
[ -f "$CATALOG_FILE" ] || CATALOG_FILE="$OWN_ROOT/i18n/catalog.en.json"
HELPER="$SCRIPT_DIR/sb_installer_helper.py"

CATALOG() {
  uv run --no-project "$HELPER" format-catalog "$CATALOG_FILE" "$@"
}

native() {
  if command -v cygpath >/dev/null 2>&1; then
    cygpath -w "$1"
  else
    printf '%s\n' "$1"
  fi
}

refuse() {
  CATALOG "$@"
  echo "VERDICT: REFUSED"
  exit 1
}

. "$SCRIPT_DIR/vault-identity.sh"

G() { git -C "$VAULT_ROOT" "$@"; }

# --- 1. Refusals before anything is touched ---------------------------------
G rev-parse --git-dir >/dev/null 2>&1 || refuse "sbUpdate.notAClone" "$(native "$VAULT_ROOT")"
DIRTY="$(G status --porcelain)"
if [ -n "$DIRTY" ]; then
  refuse "sbUpdate.dirty" "$(printf '%s\n' "$DIRTY" | cut -c4- | head -n 5 | tr '\n' ' ')"
fi
ID_BEFORE="$(vid_get "$VAULT_ROOT" vault_id)"
[ "$(vid_get "$VAULT_ROOT" status)" = "generated" ] && [ -n "$ID_BEFORE" ] \
  || refuse "sbUpdate.noIdentity" "$(native "$VAULT_ROOT/VAULT-IDENTITY.md")"
ORIGIN="$(G config --get remote.origin.url 2>/dev/null | head -n 1)"
[ -n "$ORIGIN" ] || refuse "sbUpdate.noOrigin"
# Before Mission 185 the installed clone kept the bootstrap's temporary
# clone as its origin (%TEMP%\second-brain-install): nothing to fetch from.
case "$(printf '%s' "$ORIGIN" | tr '\\' '/' | sed 's#/*$##')" in
  */second-brain-install) refuse "sbUpdate.temporaryOrigin" "$ORIGIN" ;;
esac
SERVER_BEFORE="$(vid_server_name "$VAULT_ROOT" 2>/dev/null || true)"
HEAD_BEFORE="$(G rev-parse HEAD)"

# --- 2. Fetch; the version must be a published tag --------------------------
G fetch --quiet --tags origin 2>/dev/null || refuse "sbUpdate.fetchFailed" "$ORIGIN"
TARGET="$(G rev-parse --verify --quiet "refs/tags/$VERSION^{commit}")"
[ -n "$TARGET" ] || refuse "sbUpdate.noSuchVersion" "$VERSION" "$ORIGIN"

# --- 3. Already there --------------------------------------------------------
if G merge-base --is-ancestor "$TARGET" HEAD; then
  CATALOG "sbUpdate.upToDate" "$VERSION"
  echo "VERDICT: UP-TO-DATE"
  exit 0
fi

abort_merge() {
  G merge --abort >/dev/null 2>&1 || true
  if [ "$(G rev-parse HEAD)" != "$HEAD_BEFORE" ]; then
    CATALOG "sbUpdate.headMoved" "$HEAD_BEFORE"
  fi
}

# --- 4. Merge, without committing yet ----------------------------------------
G -c merge.renames=true merge --no-ff --no-commit --quiet "refs/tags/$VERSION" >/dev/null 2>&1
CONFLICTS="$(G diff --name-only --diff-filter=U)"
if [ -n "$CONFLICTS" ]; then
  OTHERS=""
  while IFS= read -r f; do
    [ -z "$f" ] && continue
    case "$(basename "$f")" in
      index.md) G checkout --theirs -- "$f" >/dev/null 2>&1 && G add -- "$f" ;;
      *) OTHERS="${OTHERS}${OTHERS:+ }$f" ;;
    esac
  done <<EOF
$CONFLICTS
EOF
  if [ -n "$OTHERS" ]; then
    abort_merge
    refuse "sbUpdate.conflict" "$VERSION" "$OTHERS"
  fi
fi

# --- 5. Identity unchanged ---------------------------------------------------
ID_AFTER="$(vid_get "$VAULT_ROOT" vault_id)"
if [ "$ID_AFTER" != "$ID_BEFORE" ] || [ "$(vid_get "$VAULT_ROOT" status)" != "generated" ]; then
  abort_merge
  refuse "sbUpdate.identityChanged" "$ID_BEFORE" "${ID_AFTER:-(none)}"
fi

# --- 6. Indexes regenerated, preflight, one guarded merge commit -------------
if [ -f "$VAULT_ROOT/tools/build-indexes.sh" ]; then
  bash "$VAULT_ROOT/tools/build-indexes.sh" "$VAULT_ROOT" >/dev/null 2>&1 || {
    abort_merge
    refuse "sbUpdate.indexesFailed" "$VERSION"
  }
  G add -A -- ':(glob)**/index.md' >/dev/null 2>&1 || true
fi
bash "$VAULT_ROOT/tools/session-preflight.sh" >/dev/null 2>&1 || true
COMMIT_OUT="$(G commit --quiet --no-edit -m "Update to second-brain $VERSION" 2>&1)"
if [ $? -ne 0 ]; then
  abort_merge
  printf '%s\n' "$COMMIT_OUT" | tail -n 20
  refuse "sbUpdate.guardiansRefused" "$VERSION"
fi

PORCELAIN="$(G status --porcelain)"
CATALOG "sbUpdate.done" "$VERSION" "$(G rev-parse --short HEAD)"
[ -z "$PORCELAIN" ] || CATALOG "sbUpdate.leftovers" "$(printf '%s\n' "$PORCELAIN" | cut -c4- | head -n 5 | tr '\n' ' ')"
SERVER_AFTER="$(vid_server_name "$VAULT_ROOT" 2>/dev/null || true)"
if [ "$SERVER_AFTER" != "$SERVER_BEFORE" ] || ! grep -q 'vid_server_name' "$VAULT_ROOT/tools/install-vault-mcp.sh" 2>/dev/null \
  || [ "$(G diff --name-only "$HEAD_BEFORE" HEAD -- tools/install-vault-mcp.sh tools/vault-mcp.py | head -n 1)" != "" ]; then
  CATALOG "sbUpdate.rerunMcp" "$(native "$VAULT_ROOT/tools/install-vault-mcp.sh")"
fi
echo "VERDICT: UPDATED"
exit 0
